- hosts: virtualmachines
  become: true
  tasks:
    - debug:
        var: ansible_os_family

    - name: "Crear repositorio yum para docker"
      yum_repository:
        name: docker-repo
        description: "Repositorio para docker"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        enabled: yes
        gpgcheck: no
      when: ansible_facts['os_family'] == 'RedHat'

    - name: "Instalar docker"
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

    - name: "Start servicio docker"
      service:
        name: "docker"
        state: started
