---
- name: scriptPlaybook
  hosts: virtualmachines
  vars:
    nombre_container: linux2022utn
    repositorio: jorgeschelotto85/linux2022utn
    version_img: 1.0.0
  tasks:
    - name: image pull
      command: docker run --name {{nombre_container}} {{repositorio}}:{{version_img}}
      register: docker_output
    - name: Chequear containers
      command: docker ps -a
      register: container_ps_output
    - name: Imprimir resultado de contenedor
      debug:
        var: docker_output.stdout_lines
    - name: Contenedores creados
      debug:
        var: container_ps_output.stdout_lines
    - name: Remover contenedor {{nombre_container}}
      command: docker container rm {{nombre_container}}
